version: '2.3'
services:
  frontend-build:
    image: node:current
    volumes:
      - ./:/src
      - ./frontend-build:/build
  nginx:
    image: fholzer/nginx-brotli
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/key.pem:/etc/nginx/key.pem:ro
      - ./nginx/cert.pem:/etc/nginx/cert.pem:ro
      - ./nginx/html:/usr/share/nginx/html:ro
    ports:
      - "55001:80"
      - "55002:8080"
    restart: always

